.changeset/rotten-news-sort.md, src/lib/components/form-field.svelte, src/lib/components/form.svelte
Exposes the following additional values from superforms as slot props via the `<Form.Root/>` component. 
- `allErrors`
- `delayed`
- `errors`
- `submitting`
- `tainted`
- `timeout`
- `validate`
- `posted`
- `fields`
- `message`
- `options`
- `formId`
- `restore`
- `capture`
- `constraints`
=> Expose more Superforms slot props

.changeset/fresh-parents-bake.md, src/lib/index.ts
This PR exports a `getFormField` helper function which must be called upon component initialization and provides some useful stores, actions, etc. when composing your own forms.
For example, if you want to create your own custom component wrappers around the provided components, `getFormField` can provide you with useful context.
For example, if I wanted to create a reusable `Form.Label` with conditional styles applied to it depending on the error state of the field, I could do something like this:
```svelte
<script lang="ts">
import { Form, getFormField } from 'formsnap';	
const { errors } = getFormField()
</script>
<Form.Label class={$errors ? "text-red-500" : "text-gray-800"}>
<slot />
</Form.Label>
```
It returns the following type:
```ts
export type FormFieldContext = {
name: string; …
```
=> Add a `getFormField` helper function

.changeset/blue-meals-watch.md, src/lib/internal/form-field.ts, src/lib/internal/types.ts
Adds the `handlers` object containing the event handler helpers as well as the `setValue` helper function to the `getFormField` return object.
=> add additional helpers to getFormField

.changeset/sour-dots-ring.md, src/lib/components/form-description.svelte, src/lib/components/form-validation.svelte, src/lib/types.ts
This PR introduces the ability to customize the underlying HTML element/tag used for the `Description` and `Validation` components. You can pass a `tag` prop to change which element is rendered.
Both elements default to `<p/>` tags. 
```svelte
<Form.Message tag="span" />
<Form.Description tag="div" />
```
=> Add `tag` prop to `Validation` & `Description`

.changeset/rotten-rocks-fly.md, src/lib/components/form-field.svelte, src/lib/internal/form-field.ts, src/lib/types.ts
Generics are weird in Svelte, this reverts some previous type abstractions that cause the type to disconnect when using the package.
=> Fix: Value typing

.changeset/sweet-toys-cover.md, README.md, content/introduction.md, content/quick-start.md, src/lib/components/form.svelte, src/routes/examples/custom-and-formsnap/+page.svelte, src/routes/examples/only-formsnap/+page.svelte
You can override this behavior by passing in a `method` prop to the `<Form.Root />`
=> Add default `method="POST"` to form

.changeset/support-refined-schema.md, src/lib/internal/super-form-patch.ts, src/routes/examples/schemas.ts
I just copied [the current definition of validators](https://github.com/ciscoheat/sveltekit-superforms/blob/d0744b8a43df7757398065a9a86ea4753a4c0a6c/src/lib/client/index.ts#L116) from [sveltekit-superform ](https://github.com/ciscoheat/sveltekit-superforms)
Fixes #45
=> Make validators accept ZodEffects to handle refined schemas

.changeset/hip-eggs-wave.md, .gitignore, package.json, src/lib/components/form-description.svelte, src/lib/components/form-field.svelte, src/lib/components/form.svelte, src/lib/internal/form-field/create-field.ts, src/lib/internal/types.ts, tests/RefinedValidation.svelte
Another attempt at fixing #45. I included a component to "test" it in the IDE but I could not write an actual component test. Playwright failed with `[vite]: Rollup failed to resolve import "$app/environment"`, which seems to be related to https://github.com/sveltejs/kit/issues/1485. [Here](https://github.com/esafak/playwright_svelte_ts) is a repo that contains the test code.
=> Add FormValidation to Field.config.schema's type

.changeset/cool-mayflies-heal.md, package.json, src/lib/components/form-checkbox.svelte, src/lib/components/form-description.svelte, src/lib/components/form-input.svelte, src/lib/components/form-label.svelte, src/lib/components/form-radio.svelte, src/lib/components/form-select.svelte, src/lib/components/form-textarea.svelte, src/lib/components/form-validation.svelte, src/lib/components/form.svelte, src/lib/types.ts
Fixes #60
The `data-fs-error` attribute is supposed to be applied to form components when an error exists on the field. It was being set in a const `attr` variable that was not reactive to the error store. This pull request fixes the issue by making the `attr` variable reactive.
=> Fix lack of reactivity of `data-fs-error`

.changeset/light-timers-press.md, .github/workflows/release.yml, src/components/ui/select/select.svelte, src/lib/components/form-control.svelte, src/lib/components/form-field.svelte, src/lib/components/form-radio.svelte, src/lib/components/form.svelte, src/lib/components/index.ts, src/lib/helpers/get-form-control.ts, src/lib/helpers/index.ts, src/lib/internal/form-field/create-actions.ts, src/lib/internal/form-field/create-control.ts, src/lib/internal/form-field/create-field.ts, src/lib/internal/form-field/create-ids.ts, src/lib/internal/form-field/index.ts, src/lib/internal/form-field/types.ts, src/lib/internal/style.ts, src/lib/internal/types.ts, src/lib/types.ts, src/routes/examples/custom-and-formsnap/+page.svelte, src/routes/examples/schemas.ts, src/routes/examples/sink/+page.server.ts, src/routes/examples/sink/+page.svelte
`Form.Control` is useful when you want to use a component other than your typical form component.
For example, you may have a button acting as the primary form control, so to get the right attributes and also automatically include an input bound to the value, you could do something like this:
```svelte
<Form.Field>
<Form.Label>My Label</Form.Label>
<Form.Control let:attrs>
<Button {...attrs}>Hello</Button>
</Form.Control>
</Form.Field>
```
Now when the label is pressed, the button will trigger, and when the form is invalid, focus will be brought to the button (if that field is invalid).
You can also pass in a custom id to use, if your element ids are controlled elsewhere:
```svelte
<Form.Field>
<Form.Label>My Label</Form.Label>
<Form.Control let:attrs id="123">
<Button …
```
=> New Component: `<Form.Control />`

.changeset/fifty-dryers-heal.md, content/api-reference/form-control.md, content/api-reference/form-root.md, src/lib/components/form-control.svelte, src/lib/components/form.svelte, src/lib/types.ts, src/routes/examples/schemas.ts, src/routes/examples/sink/+page.server.ts, src/routes/examples/sink/+page.svelte
This PR introduces a feature that closes a lot of outstanding issues and will make the library more robust overall. It should not introduce any breaking changes to existing projects, if it does please [open an issue](https://github.com/huntabyte/formsnap/issues/new)
Controlled usage is designed to be used when you need a higher level of control over the form state. To make a form controlled, you simply set the `controlled` prop to `true`, and pass the object returned from the `superForm` function to the `form` prop.
Now rather than initializing the `SuperForm` on your behalf, we simply use what you pass to the `form` prop. This allows you to initialize the form wherever you'd like, as well as control it from outside the `<Form.Root />` component.
When using controlled usage, you still …
=> Feat: Controlled `SuperForm` usage

.changeset/grumpy-papayas-sparkle.md, src/lib/components/form-input.svelte, src/lib/components/form-radio.svelte, src/lib/components/form-textarea.svelte
I updated the data-fs-select data attribute assigned to the input, textarea and radio components related to issue #93 (and my own experience).  I didn't notice any comments indicated if this was intention, but feel free to reject if it intentional design!  Just wanted to help in case it was just a copy paste error :)
Closes: #93
=> fix: apply correct data attributes to elements

content/quick-start.md
Quick fix for spelling `z.enum()` in the quick start section of docs.
=> fix: spelling of z.enum() in quick-start

README.md, content/quick-start.md
This is required in SvelteKit 2.
Superforms already have this in the docs: https://superforms.rocks/get-started#initializing-the-form-in-the-load-function
Closes #105
=> Docs: Use await superValidate in load function

content/quick-start.md
- Added the missing marketingEmails field missing in the quick start example
Also unlike shadcn-svelte it's missing title and instead shows the full url
I checked the code and it was same as shadcn docs, if you can point me what to fix i can help you with it 😄 
Also why does it have svelte default logo 😳 (never noticed before)
=> fix: added missing field to the quick start example

sites/docs/src/lib/config/navigation.ts
Reorders the "Components" sidebar into a more intuitive order.
=> docs: reorder navigation

sites/docs/content/quick-start.md
To be consistent with Superforms docs suggest we drop /server and import from top level instead given v2
=> docs: update quick-start.md

packages/formsnap/src/lib/components/types.ts, sites/docs/content/components/element-field.md, sites/docs/content/components/field.md
Hello
I was copy pasting the example here https://www.formsnap.dev/docs/components/field and saw a type error.
When i changed "contraints" to "constraints" it worked for me.
I saw that this typo was in multiple places and changed it there too.
=> fix: typos contraints to constraints

.changeset/small-zoos-check.md, packages/formsnap/package.json
Resolves npm 7+ peer dependency errors
=> chore: support Svelte 5 peer dep

.changeset/loud-students-mate.md, sites/docs/content/quick-start.md
Just noticed this was missing.
=> docs: fix quick start missing import in docs field
